[package]
name = "astral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
polars = "0.38.1"
pyo3 = "0.20.3"
pyo3-polars = "0.12.0"
safetensors = "0.4.2"
tch = "0.15.0"
